### ISSUE TITLE
Keep two variants: Zalando + Baloise

### ISSUE THREAD

**Issue by christiansiegel** [baloise-incubator/spectral-ruleset#12]
There is an interest for Zalando rules for spectral: https://github.com/zalando/restful-api-guidelines/issues/544#issuecomment-920039645 

Why not keep two variants of the ruleset?: one with the 1:1 Zalando rules plus one that extends it with Baloise specifics. Spectral makes such extensions quite simple.

This way the Zalando part could gain some traction in the open source community.

**Comment by leubedane** [comment]
Do you have an idea to hold both variants? Make two spectral.yml files or clone the repo?

**Comment by christiansiegel** [comment]
I would keep it in the same repo:
- `zalando.yml` defining all the rules
- `baloise.yml` extending the `zalando.yml` and adding/removing some rules
- Maybe keep a `.spectral.yml` as a 'default' that extends either `zalando.yml` or `baloise.yml`

Even the testing setup can almost stay the same. You only need to use the baloise ruleset for the `***-a` rules
```yaml
# baloise.yml
extends:
- ./zalando.yml
rules:
  must-have-info-contact-name: off # disable
  must-have-info-contact-email: warn # change severity
  must-have-info-contact-url: # redefine the whole thing
    # [...]
  # ..or add more baloise rules
```
```yaml
# .spectral.yml
extends:
- ./zalando.yml
```
