### ISSUE TITLE
must-use-lowercase-with-hypens-for-path-segements regex catastrophic failure

### ISSUE THREAD

**Issue by puittenbroek** [baloise-incubator/spectral-ruleset#32]
Hello! Was testing your nice set of rules, but ran into a snag with one of the rules.
The performance was utterly terrible, suddenly taking 12 minutes!

Boils down to this [regex](https://github.com/baloise-incubator/spectral-ruleset/blob/main/zalando.yml#L95) failing utterly if a underscore is introduced. If the underscore is in the first part of the URL, it works. 2nd and beyond it breaks hard.

See online regex [here](https://regex101.com/r/y1DLuR/1) for an example that breaks with an "Catastrophic backtracking has been detected".

My work around now is to make a script out of it that splits on `/` and checks each part of the url.

```yaml
functions: [must-use-lowercase-with-hypens-for-path-segements]
rules:
  must-use-lowercase-with-hypens-for-path-segements:
    message: Path segments have to be lowercase separate words with hyphens
    description: MUST use lowercase separate words with hyphens for path segments [129]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#129
    severity: error
    given: $.paths.*~
    then:
      function: "must-use-lowercase-with-hypens-for-path-segements"```
```
And the script (not my best work, just to illustrate).

```javascript
const rePathParam = new RegExp('^(\{.*\})$');
const reRegularHypenedWord = new RegExp('^([\/a-z][a-z0-9\-\/]*)$');


const check = (path) => {
  const parts = path.split('/');
  parts.forEach((part) => {
    if (part != '' && !part.match(rePathParam) && !part.match(reRegularHypenedWord)){
      console.log(part, part.match(rePathParam), part.match(reRegularHypenedWord));
      throw 'Path must only use hypens and lower case!';
    }
  });
};


export default path => {
  try {
    check(path);
  } catch (ex) {
    return [
      {
        message: ex,
      },
    ];
  }
};
```
