### ISSUE TITLE
Rule crash: should-declare-enum-values-using-upper-snake-case-format

### ISSUE THREAD

**Issue by nmoreaud** [baloise-incubator/spectral-ruleset#34]
On my API specification, this rule crashes:

```yaml
  should-declare-enum-values-using-upper-snake-case-format:
    message: 'Enum values should be in UPPER_SNAKE_CASE format'
    description: SHOULD declare enum values using UPPER_SNAKE_CASE format [240]
    documentationUrl: https://opensource.zalando.com/restful-api-guidelines/#240
    severity: warn
    given: $.paths..[?(@.type=='string')].[enum,x-extensible-enum].*
    then:
      function: pattern
      functionOptions:
        match: ^[A-Z][A-Z_0-9]*$
```

Error:
```
evalmachine.<anonymous>:1
_$_v.type=='string'
     ^

TypeError: Cannot read properties of null (reading 'type')
    at evalmachine.<anonymous>:1:6
    at Script.runInContext (node:vm:140:12)
    at Script.runInNewContext (node:vm:145:17)
    at Object.runInNewContext (node:vm:299:38)
    at JSONPath._eval (/home/dev/.npm/_npx/ead2125907eeaeca/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:643:20)
    at /home/dev/.npm/_npx/ead2125907eeaeca/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:420:16
    at /home/dev/.npm/_npx/ead2125907eeaeca/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:576:7
    at Array.forEach (<anonymous>)
    at JSONPath._walk (/home/dev/.npm/_npx/ead2125907eeaeca/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:575:22)
    at JSONPath._trace (/home/dev/.npm/_npx/ead2125907eeaeca/node_modules/nimma/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:419:10)
Error running Spectral!
Error #1: jsonPath: Cannot read properties of null (reading 'type'): _$_v.type=='string'
          at _eval    …ex-node-cjs.cjs:647  throw new Error('js…
          at          …ex-node-cjs.cjs:420  if (this._eval(l.re…
          at          …ex-node-cjs.cjs:576  f(m, loc, expr, val…
          at forEach                                            
          at _walk    …ex-node-cjs.cjs:575  Object.keys(val).fo…
```
